depguard:
  rules:
    Main:
      files:
        - $all
        - "!$test"
      allow:
        - $gostd
    Test:
      files:
        - $test
      allow:
        - $gostd
        - github.com/stretchr/testify